# Cloudflare Pages + D1 (public site)
name = "ledian-clinic"
compatibility_date = "2025-01-01"

# Astro build output for public site
pages_build_output_dir = "apps/public-site/dist"

[[d1_databases]]
binding = "DB"
database_name = "ledian-public-prod"
database_id = "1528077a-91e3-421f-adab-38e7fd412734"
preview_database_id = "37a6de04-9beb-4f46-9531-653fe3fb64d7"
migrations_dir = "database/d1/migrations"

[[kv_namespaces]]
binding = "SESSION"
id = "afb97d65c9884920b922190ad862888a"
preview_id = "c7f7337e790f415d81b77713bf934051"
